# Generated by Django 5.2.17 on 2026-09-23 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('resolved', 'Выполнена'), ('closed', 'Закрыта')], max_length=20, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('resolved', 'Выполнена'), ('closed', 'Закрыта')], max_length=20, verbose_name='Новый статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tickets.ticket', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Изменение статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
